//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.DonThuocs = new HashSet<DonThuoc>();
        }
    
        public int MaPhieuKham { get; set; }
        public Nullable<int> MaBenhNhan { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string TrieuChung { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuoc> DonThuocs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
